Done
firte07/Food-ordering pull request #1
Opened 2021-04-11 20:30 UTC by firte07

Am o problema de vizualizare in github pages (la partea din main de grid, imaginile nu sunt incadrate ok, desi pe live coding-ul pe care l-am folosit din VS code imi incadra ok --vezi si drive--).

2021-04-12 08:09 UTC, firte07 commented
Aici e link-ul catre github pages:  https://firte07.github.io/Food-ordering/

2021-04-12 09:17 UTC, chioreandan requested changes
Nice Job, 
Need to pay more attention to the naming conventions, spacing, and indentation

2021-04-12 09:17 UTC, chioreandan commented on index.html
> +                  </nav>
indentation here is off for nav

2021-04-12 09:17 UTC, chioreandan commented on script.js
> +function handleMouseOver(x){
What is x? please rename this variable

2021-04-12 09:17 UTC, chioreandan commented on style.css
> +
remove empty line

2021-04-12 09:17 UTC, chioreandan commented on style.css
> +.a, .b, .c, .d, .e, .f, .g, .h {
what is this? why do you need so many classes?

2021-04-12 09:17 UTC, chioreandan commented on style.css
> +
remove empty lines

2021-04-12 09:17 UTC, chioreandan commented on index.html
> +                    </p>
Indentation is off here

2021-04-12 09:17 UTC, chioreandan commented on index.html
> +
remove empty line

2021-04-12 09:17 UTC, chioreandan commented on index.html
> +
remove empty line

2021-04-12 10:01 UTC, firte07 commented on style.css
> +.a, .b, .c, .d, .e, .f, .g, .h {
to access each image individually, but right now I realized that it's easier to have a single class for all (because i didn't use them individually)

2021-04-13 07:11 UTC, AdrianFlorian requested changes
Getting there, Cata! Please add a descriptive title to the PR and a good description of the changes. Use this as an inspiration: https://github.com/cristichirtos/RoR-internship-assignment-1/pull/1

2021-04-13 07:46 UTC, chioreandan requested changes
Looks good,
Some 2 small request changes. Also, try to add an empty line a the end of each file. you can add this in you vscode settings: "files.insertFinalNewline": true,

2021-04-13 07:46 UTC, chioreandan commented on style.css
> +*/
remove comments

2021-04-13 07:46 UTC, chioreandan commented on style.css
> +
remove empty line

2021-04-14 07:08 UTC, firte07 commented
The last changes in this PR:

- remove comments and empty lines from style.css
- add a new empty lines at the end of the code for all files
- add classes for the native HTML components and make changes in style.css

2021-04-15 06:24 UTC, chioreandan requested changes
@firte07 please review your pull request again. Please be more careful with the spacing and also when overriding the native HTML component.

2021-04-15 06:24 UTC, chioreandan commented on style.css
> +}
What if you need to use h1, h2, h4 in another part of the page but with different styling.

2021-04-15 06:24 UTC, chioreandan commented on style.css
> +.aboutus{
empty space is missing here after the name of the class

2021-04-15 06:24 UTC, chioreandan commented on style.css
> +.ingredients{
same

2021-04-15 07:54 UTC, firte07 commented
The last changes in this PR:

- add classes for the native HTML components and make changes in style.css
- put spaces after the name of the classes
- indent HTML code

2021-04-15 09:34 UTC, AdrianFlorian commented
@firte07 Can you please add a descriptive title to the PR and a good description of the changes (in the PR description). Use this as an inspiration: cristichirtos/RoR-internship-assignment-1#1

2021-04-15 10:07 UTC, firte07 commented
@AdrianFlorian

2021-04-15 16:07 UTC, AdrianFlorian approved these changes

2021-04-15 16:08 UTC, AdrianFlorian commented
nice job @firte07  ;)

2021-04-16 13:37 UTC, firte07 commented
@chioreandan can you please make a new review?

2021-04-19 07:40 UTC, chioreandan approved these changes
Looks good to me @firte07 👍

2021-04-19 07:43 UTC, merged